### ISSUE TITLE
JNI:GetDeviceName:java.lang.SecurityException when initializing Sentry when targeting Android API level 32 or later

### ISSUE THREAD

**Issue by travis-tap-3d** [getsentry/sentry-unity#1322]
### Environment

How do you use Sentry?

Sentry SaaS (sentry.io)

Which version of the SDK?

1.2.0

How did you install the package? (Git-URL, Assetstore)

Git-URL

Which version of Unity?

2021.3.23f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?

Android player

### Steps to Reproduce

Integrate Sentry into a Unity Android project and set the API minimum and target level to 32.

### Expected Result

Initializes without an exception. API 32 is a requirement for some devices in future such as Oculus Quest

### Actual Result

Logs show this exception when  trying to initialize the Sentry SDK:

```
_AndroidPlayer "Oculus_Quest" JNI:AndroidPlayer "Oculus_Quest" JNI:GetDeviceName:java.lang.SecurityException: Settings key: <bluetooth_name> is only readable to apps with targetSdkVersion lower than or equal to: 31
Sentry.Unity.SentryMonoBehaviour:CollectData()
UnityEngine.GameObject:AddComponent()
Sentry.Unity.SentryMonoBehaviour:get_Instance()
Sentry.Unity.ScriptableSentryUnityOptions:ToSentryUnityOptions(Boolean, ISentryUnityInfo, IApplication)
Sentry.Unity.SentryInitialization:Init()

[PlatformDependent/AndroidPlayer/Source/DVM.h line 1703435192]_
```

**Comment by bitsandfoxes** [comment]
Thanks for reporting this. I'm giving this a go locally.

**Comment by bitsandfoxes** [comment]
Looks like requesting `[SystemInfo.deviceName](https://docs.unity3d.com/ScriptReference/SystemInfo-deviceName.html)` and `targetSdkVersion 32` don't get along.

**Comment by bitsandfoxes** [comment]
Hey, I just looked at putting in the workaround but I can't seem to reproduce this on an actual phone. Is this happening for you on the Oculus Quest only?

**Comment by travis-tap-3d** [comment]
Hmm I only have a Quest as our product isn't on mobile so unfortunately I'm unable to test that for you. That'd be surprising since I assume it would be specific to any Android device with that version.

**Comment by bitsandfoxes** [comment]
Resolved by https://github.com/getsentry/sentry-unity/pull/1365 and shipped with `1.5.0`

**Comment by travis-tap-3d** [comment]
Unfortunately I still see the error after upgrading to 1.5.0. Luckily, it doesn't seem to block/prevent anything from working that I see but an FYI:

_"AndroidPlayer "Oculus_Quest" JNI:GetDeviceName:java.lang.SecurityException: Settings key: <bluetooth_name> is only readable to apps with targetSdkVersion lower than or equal to: 31"_

**Comment by bitsandfoxes** [comment]
Thanks for letting us know. We're still trying to fetch the DeviceName, the SDK just doesn't blow up during initialization. IMO this is something Unity should resolve.
