### ISSUE TITLE
Updated link.xml would not override existing one

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#287]
We should make sure to override outdated data.

**Comment by bitsandfoxes** [comment]
When taking a look at this please also note: https://github.com/getsentry/sentry-unity/issues/521

**Comment by bitsandfoxes** [comment]
And this: https://github.com/getsentry/sentry-unity/issues/81

**Comment by bruno-garcia** [comment]
I believe this was resolved, no?

**Comment by bitsandfoxes** [comment]
Still doesn't override. We have not yet updated the link.xml once.

**Comment by bruno-garcia** [comment]
Instead of opening a new issue this seems like the right spot to discuss:

Should we revisit if we really need link.xml now? Some of the rules added there were from 2018 when the Sentry SDK for .NET used `Newtonsoft.Json` with reflection. Now the serialization is mostly done manually. Only bits with reflection are what's set in `Event.Contexts` or `Event.Extra`.

**Comment by bruno-garcia** [comment]
If the issue is overriding things added manually by the user, is this something we should even do?
They should have their own link.xml file, right?

**Comment by bitsandfoxes** [comment]
Yes, users have their own. It was just a general observation that there is nothing in place that would override an already existing link.xml if we were to update.
Another thing: We never updated it after introducing aliasing. Why and how does it still work - I do not know.
