### ISSUE TITLE
Game Crashed on Nintendo Switch with Sentry SDK

### ISSUE THREAD

**Issue by dimmduh** [getsentry/sentry-unity#290]
### Environment

How do you use Sentry?
on-premise

Which SDK and version?
0.4.3

### Steps to Reproduce

1. Run game with sdk

### Expected Result

Not crashing.

### Actual Result

Game crashed.
I guess it's because of trying to write to disk incorrect way.

**Comment by bitsandfoxes** [comment]
Hey @dimmduh, thanks for raising this! You're most likely right. The Sentry SDK relies on `Application.persistentdatapath` to provide offline caching which seems to be prohibited on the Switch. A workaround would be to disable auto session tracking and offline caching. (and setting the `CacheDirectoryPath` to null).
We'll look into a platform-specific solution for this.

**Comment by bruno-garcia** [comment]
An update here, we'll get a dev device soon to test this out

**Comment by dimmduh** [comment]
Notice, there is restriction, you can not collect and send any analytics on device. SDK will work only in development mode.

**Comment by bruno-garcia** [comment]
> Notice, there is restriction, you can not collect and send any analytics on device. SDK will work only in development mode.

Could you please provide some context about this? Where can we find more information?

**Comment by dimmduh** [comment]
> > Notice, there is restriction, you can not collect and send any analytics on device. SDK will work only in development mode.
> 
> Could you please provide some context about this? Where can we find more information?

sorry, I can not because of NDA. You need Nintendo developer account to access documentation

**Comment by bruno-garcia** [comment]
We have a Nintendo Dev account. We'll take a look at the docs and investigate this further.

**Comment by bruno-garcia** [comment]
An update, we were able to find out what the issue is. And when we add WebGL support, it should fix this too.

**Comment by vaind** [comment]
We just need to make sure we add the `UnityWebRequestTransport` for all platforms other than mobile and desktop - that should fix the issues on consoles as well.

**Comment by bruno-garcia** [comment]
It still crashes due to file access. See: https://github.com/getsentry/sentry-dotnet/issues/1726

We need to set `AutoSessionTracking` to false for unknown platforms
