### ISSUE TITLE
IL2CPP Windows 2019.4.35+ - Try block ends without any catch, finally, nor fault handler

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#550]
Android builds fail on Windows with IL2CPP with: `Try block ends without any catch, finally, nor fault handler`.
Sample in CI: https://github.com/getsentry/sentry-unity/runs/5049914009?check_suite_focus=true

Works on macOS with the same version.
Works on 2019.4.34f1
Has been reported.

**Comment by SlavomirDurej** [comment]
Please fix this as soon as possible, we can't publish our game in build < 2019.4.35f1 as we need to split binaries (supported only  from build 2019.4.29f1) but theres an important bug fixed in 2019.4.35f1, so that's the only version we can actually use!

**Comment by bruno-garcia** [comment]
It's not rally a bug in Sentry's SDK. We've reported it to Unity already.

**Comment by SlavomirDurej** [comment]
> It's not rally a bug in Sentry's SDK. We've reported it to Unity already.

OK, but perhaps you can still try and add that catch clause in GlobalSessionManager::TryRecoverPersistedSession() right? 

Your library is the only one that seems to trigger this issue...

**Comment by rainbowcreatures** [comment]
Hey @bruno-garcia , do you know if there's a workaround for this issue? Does Unity optimize out an empty catch/finally or whatever block(judging by the weird error)? If yes, could that be worked around until Unity comes up with a fix. We also have this issue that we're using split binaries, which have been pretty buggy(random crashes for some devices), until a fix finally implemented in 35f1. Ironically, 35f1 now causes Sentry to break. So we can't use split binary with Sentry both :(

**Comment by bruno-garcia** [comment]
> > It's not rally a bug in Sentry's SDK. We've reported it to Unity already.
> 
> OK, but perhaps you can still try and add that catch clause in GlobalSessionManager::TryRecoverPersistedSession() right?
> 
> Your library is the only one that seems to trigger this issue...

It's likely because we're the only ones using [Exception filters](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/using-user-filtered-exception-handlers).
If there's no easy way around it, we might just change our code to remove the exception filters but that's a downgrade on our code and we'd like Unity to fix this instead before we take that route.

**Comment by bruno-garcia** [comment]
> Hey @bruno-garcia , do you know if there's a workaround for this issue? Does Unity optimize out an empty catch/finally or whatever block(judging by the weird error)? If yes, could that be worked around until Unity comes up with a fix. We also have this issue that we're using split binaries, which have been pretty buggy(random crashes for some devices), until a fix finally implemented in 35f1. Ironically, 35f1 now causes Sentry to break. So we can't use split binary with Sentry both :(

If we don't hear back from Unity in the next 4 days (I'm writing this on a Sunday) we can patch our SDK to get rid of Exception filters. It's just really annoying that we need to change properly working code into a less efficient version because Unity introduced a regression on their tooling.

**Comment by SlavomirDurej** [comment]
> > Hey @bruno-garcia , do you know if there's a workaround for this issue? Does Unity optimize out an empty catch/finally or whatever block(judging by the weird error)? If yes, could that be worked around until Unity comes up with a fix. We also have this issue that we're using split binaries, which have been pretty buggy(random crashes for some devices), until a fix finally implemented in 35f1. Ironically, 35f1 now causes Sentry to break. So we can't use split binary with Sentry both :(
> 
> If we don't hear back from Unity in the next 4 days (I'm writing this on a Saturday) we can patch our SDK to get rid of Exception filters. It's just really annoying that we need to change properly working code into a less efficient version because Unity introduced a regression on their tooling.

Thank you Bruno, appreciate your response! 

What if Unity comes back with : We (might/will) include a solution for this in the next LTS 2019.4.36f build, but without ETA? Would you be able to patch this up until they do?

**Comment by bruno-garcia** [comment]
Should be resolved on: https://github.com/getsentry/sentry-unity/releases/tag/0.10.0

**Comment by SlavomirDurej** [comment]
Hi Bruno, thank you but unfortunately it still doesn't compile properly :( Just got this error when building with your latest version 
`IL2CPP error for method 'System.Boolean System.Text.Json.Serialization.JsonConverter`1::WriteCore(System.Text.Json.Utf8JsonWriter,T&,System.Text.Json.JsonSerializerOptions,System.Text.Json.WriteStack&)' in assembly 'E:\MuseumHOGMeta\Temp\StagingArea\assets\bin\Data\Managed\Sentry.System.Text.Json.dll'
Additional information: Try block ends without any catch, finally, nor fault handler`

**Comment by bitsandfoxes** [comment]
I was just running it through CI: https://github.com/getsentry/sentry-unity/runs/5197577209?check_suite_focus=true with the same issue:

> `IL2CPP error for method 'System.Boolean System.Text.Json.Serialization.JsonConverter`1::WriteCore(System.Text.Json.Utf8JsonWriter,T&,System.Text.Json.JsonSerializerOptions,System.Text.Json.WriteStack&)' in assembly 'E:\MuseumHOGMeta\Temp\StagingArea\assets\bin\Data\Managed\Sentry.System.Text.Json.dll'
> Additional information: Try block ends without any catch, finally, nor fault handler`

**Comment by bruno-garcia** [comment]
Well, another issue to be open with unity and this time, nothing we can do.

**Comment by SlavomirDurej** [comment]
> Well, another issue to be open with unity and this time, nothing we can do.

This is really disappointing, we were quite relying on Sentry for bug tracking, but also your great Send Feedback functionality!

Is this because you can't add the catch clause to the JSON Converter class, it being a system library? Would you be able to use 3rd party json serializer instead perhaps?

**Comment by bruno-garcia** [comment]
> This is really disappointing, we were quite relying on Sentry for bug tracking, but also your great Send Feedback functionality!

I understand that, it's really frustraiting to us too. But another work around would require rewriting all serialization code from `System.Text.Json`, and since the built-in is limited in ways, we'd need to write new protocol C# classes too, to help Unity's serializer. At that point it's easier to just get back to [Unity Lite SDK](https://github.com/getsentry/sentry-unity-lite)

This is because IL2CPP on Windows from Unity 2019.4.35f can't handle a C# exception filter.
It works on that version of Unity on a Mac. It works on Windows on a previous LTS version.
I opened a [forum post here](https://forum.unity.com/threads/il2cpp-error-try-block-ends-without-any-catch-finally-nor-fault-handler.1240507/) to try to get some help from Unity folks.

Hopefully this will be addressed quickly on their end so we don't need to take any drastic measures on our end (as in refactoring all protocol/serialization).

**Comment by vaind** [comment]
Is the unity forum the best place to report errors? Maybe we should be doing that the unity editor or hub instead? There's a "Report a bug" menu in both...

**Comment by bruno-garcia** [comment]
> @bruno-garcia there was a LTS build released yesterday, [unity3d.com/unity/whats-new/2019.4.36](https://unity3d.com/unity/whats-new/2019.4.36)
> 
> Looking at what's new, it doesn't look like they've fixed this issue?

I read their changelog and couldn't spot anything that indicates this issue was addressed.
Sounds like we're using it already in CI (but on Linux only): https://github.com/getsentry/unity-docker/blob/e7c50834ccfb0aad7029158a24a8cb5719e284db/.github/workflows/ci.yml#L26-L33

The CI here/Windows steps are still on 34f which is before the bug was introduced: https://github.com/getsentry/sentry-unity/blob/97949af1b210738c58be39f287ea22f0bb015a03/.github/workflows/ci.yml#L56

We can try bumping the Windows to 36 to see if it's resolved

**Comment by vaind** [comment]
it's still the same issue on 2019.4.36f1 (I've tried locally)

**Comment by bitsandfoxes** [comment]
Tracked by Unity: https://issuetracker.unity3d.com/issues/il2cpp-build-fails-on-try-block-ends-without-any-catch-finally-nor-fault-handler

**Comment by vaind** [comment]
Unity: "Fixed in: 2019.4.38f1"

Let's hope it's true
